@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	RollRandomLevelVariant
	.type	 RollRandomLevelVariant,function
	.thumb_func
RollRandomLevelVariant:
	bx	lr
.Lfe1:
	.size	 RollRandomLevelVariant,.Lfe1-RollRandomLevelVariant
	.comm	gGameFlags, 4	@ 4
